#!/usr/bin/env python3
"""
Git Integration for ContextWolf
Auto-installs hooks and tracks commits automatically.
"""

import os
import sys
import subprocess
import time
from pathlib import Path
from typing import Optional, Dict, Any


class GitIntegration:
    """Handles Git repository detection and hook management"""

    HOOK_MARKER = "# AUTO-GENERATED BY CONTEXTWOLF"
    HOOK_VERSION = "2026-04-05"

    @staticmethod
    def is_interactive() -> bool:
        """Check if we're in an interactive environment"""
        if os.environ.get('CI'):
            return False
        if not sys.stdin.isatty():
            return False
        if os.environ.get('CLAUDE_CODE'):
            return False
        if not sys.stdout.isatty():
            return False
        return True

    def __init__(self):
        """Initialize Git integration"""
        pass

    def is_git_repo(self, path: Path = None) -> bool:
        """Check if current/given directory is a git repository"""
        if not path:
            path = Path.cwd()
        return (path / '.git').exists()

    def has_cm_hook(self, path: Path = None) -> bool:
        """Check if repo has our hook installed AND it's the current version"""
        if not path:
            path = Path.cwd()

        hook_path = path / '.git' / 'hooks' / 'post-commit'
        if not hook_path.exists():
            return False

        try:
            content = hook_path.read_text()
            is_cm = "CONTEXTWOLF" in content or "CONTEXT-MANAGER" in content
            if not is_cm:
                return False
            is_current = f"Hook Version: {self.HOOK_VERSION}" in content
            return is_current
        except Exception:
            return False

    def get_git_info(self, path: Path = None) -> Optional[Dict[str, Any]]:
        """Get current git repository information"""
        if not path:
            path = Path.cwd()

        if not self.is_git_repo(path):
            return None

        try:
            info = {}

            result = subprocess.run(
                ['git', 'branch', '--show-current'],
                cwd=path, capture_output=True, text=True
            )
            info['branch'] = result.stdout.strip() if result.returncode == 0 else 'unknown'

            result = subprocess.run(
                ['git', 'rev-parse', 'HEAD'],
                cwd=path, capture_output=True, text=True
            )
            info['last_commit'] = result.stdout.strip()[:8] if result.returncode == 0 else None

            result = subprocess.run(
                ['git', 'remote', 'get-url', 'origin'],
                cwd=path, capture_output=True, text=True
            )
            if result.returncode == 0:
                remote_url = result.stdout.strip()
                if '/' in remote_url:
                    info['repo_name'] = remote_url.rstrip('/').split('/')[-1].replace('.git', '')
                else:
                    info['repo_name'] = path.name
            else:
                info['repo_name'] = path.name

            result = subprocess.run(
                ['git', 'status', '--porcelain'],
                cwd=path, capture_output=True, text=True
            )
            info['has_changes'] = bool(result.stdout.strip()) if result.returncode == 0 else False

            return info

        except Exception as e:
            print(f"Error getting git info: {e}")
            return None

    def generate_hook_content(self) -> str:
        """Generate the post-commit hook content.

        Uses the `cm` CLI command (installed via uv/pip).
        No hardcoded paths - works on any machine where cm is installed.
        """
        return f'''#!/bin/bash
{self.HOOK_MARKER} - DO NOT EDIT
# Hook Version: {self.HOOK_VERSION}
# This hook automatically tracks git commits in ContextWolf

# Get commit info
MESSAGE=$(git log -1 --pretty=format:%s)
PROJECT=$(basename "$(pwd)")
HASH=$(git rev-parse --short HEAD)
BRANCH=$(git branch --show-current)
AUTHOR=$(git log -1 --pretty=format:"%an")
FILES=$(git diff-tree --no-commit-id --name-only -r HEAD | head -20 | tr '\\n' ' ')
STATS=$(git diff --stat HEAD~1..HEAD 2>/dev/null | tail -1)

# Build metadata JSON
METADATA=$(cat <<JSONEOF
{{"commit_hash": "$HASH", "branch": "$BRANCH", "author": "$AUTHOR", "files_changed": "$FILES", "stats": "$STATS"}}
JSONEOF
)

# Save to ContextWolf (cm must be in PATH)
cm save "Git commit: $MESSAGE" --type commit --project "$PROJECT" --metadata "$METADATA" > /dev/null 2>&1

# Always exit successfully to not block git
exit 0
'''

    def install_hook(self, path: Path = None, force: bool = False) -> bool:
        """Install the post-commit hook in a git repository"""
        if not path:
            path = Path.cwd()

        if not self.is_git_repo(path):
            print(f"❌ {path} is not a Git repository!")
            return False

        hooks_dir = path / '.git' / 'hooks'
        hooks_dir.mkdir(exist_ok=True)

        hook_path = hooks_dir / 'post-commit'

        if hook_path.exists() and not force:
            if self.has_cm_hook(path):
                print("✅ ContextWolf hook is already installed and up to date!")
                return True
            else:
                # Check if it's an outdated CM hook (auto-update without asking)
                try:
                    content = hook_path.read_text()
                    is_old_cm = "CONTEXTWOLF" in content or "CONTEXT-MANAGER" in content
                except Exception:
                    is_old_cm = False

                if is_old_cm:
                    print(f"🔄 Outdated ContextWolf hook found - updating to {self.HOOK_VERSION}")
                else:
                    print(f"⚠️  {hook_path} exists (not from ContextWolf)")
                    if not self.is_interactive():
                        return False
                    response = input("Overwrite existing hook? [y/N]: ")
                    if response.lower() != 'y':
                        print("❌ Installation cancelled.")
                        return False

        try:
            hook_content = self.generate_hook_content()
            hook_path.write_text(hook_content)
            hook_path.chmod(0o755)

            print(f"✅ Git hook installed in {hook_path}")
            print("📝 All commits will be automatically tracked in ContextWolf!")
            return True

        except Exception as e:
            print(f"❌ Error installing hook: {e}")
            return False

    def prompt_for_installation(self, path: Path = None) -> bool:
        """Prompt user to install git hook"""
        if not path:
            path = Path.cwd()

        if not self.is_interactive():
            return False

        git_info = self.get_git_info(path)
        if not git_info:
            return False

        print(f"\n🎣 Git repository detected: {git_info['repo_name']}")
        print(f"   Branch: {git_info['branch']}")
        if git_info['last_commit']:
            print(f"   Last commit: {git_info['last_commit']}")

        print("\n📌 Enable automatic commit tracking?")
        print("   This installs a post-commit hook that saves each commit to ContextWolf.")

        response = input("\n[Y/n]: ").strip().lower()

        if response in ['', 'y', 'yes', 'ja', 'j']:
            return self.install_hook(path)
        else:
            print("⏭️  Git hook installation skipped.")
            return False

    def check_and_prompt(self, path: Path = None) -> None:
        """Check if in git repo and prompt for hook installation if needed"""
        if not path:
            path = Path.cwd()

        if not self.is_interactive():
            return

        if self.is_git_repo(path) and not self.has_cm_hook(path):
            marker_file = path / '.git' / '.cm_hook_prompted'

            if marker_file.exists():
                try:
                    mtime = marker_file.stat().st_mtime
                    days_ago = (time.time() - mtime) / (24 * 3600)
                    if days_ago < 7:
                        return
                except Exception:
                    pass

            self.prompt_for_installation(path)

            try:
                marker_file.touch()
            except Exception:
                pass

    def setup_global_template(self) -> bool:
        """Setup global git template for all new repositories"""
        template_dir = Path.home() / '.git-template' / 'hooks'
        template_dir.mkdir(parents=True, exist_ok=True)

        hook_path = template_dir / 'post-commit'

        try:
            hook_content = self.generate_hook_content()
            hook_path.write_text(hook_content)
            hook_path.chmod(0o755)

            subprocess.run(
                ['git', 'config', '--global', 'init.templatedir', str(template_dir.parent)],
                check=True
            )

            print(f"✅ Global git template installed in {template_dir.parent}")
            print("📝 All new git repos will automatically have the ContextWolf hook!")
            return True

        except Exception as e:
            print(f"❌ Error setting up global template: {e}")
            return False
